'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const { detectAgent } = require('../src/checks/detect');

const CFG = {
  labels: ['codex-generated', 'agentic'],
  branchPrefixes: ['codex/', 'gh-codex/'],
  keywords: ['generated by codex', 'generated by claude'],
};

test('detects by label (case-insensitive)', () => {
  const r = detectAgent(
    { labels: ['TASK-123', 'Codex-Generated'], headBranch: 'feat/foo', title: 'x' },
    CFG
  );
  assert.equal(r.agent, true);
  assert.match(r.signal, /label/);
});

test('detects by branch prefix', () => {
  const r = detectAgent(
    { labels: [], headBranch: 'codex/feat/auth', title: 'x' },
    CFG
  );
  assert.equal(r.agent, true);
  assert.match(r.signal, /branch/);
});

test('detects by title keyword', () => {
  const r = detectAgent(
    { labels: [], headBranch: 'feat/auth', title: 'refactor: generated by Codex' },
    CFG
  );
  assert.equal(r.agent, true);
  assert.match(r.signal, /title/);
});

test('returns false when nothing matches', () => {
  const r = detectAgent(
    { labels: ['bug'], headBranch: 'feat/auth', title: 'fix: login' },
    CFG
  );
  assert.equal(r.agent, false);
});
