'use strict';

/**
 * Decide whether a pull request was generated by an AI coding agent.
 *
 * A PR counts as agent-generated when any of the configured signals match:
 *  - a label on the PR (e.g. "codex-generated")
 *  - the head branch prefix (e.g. codex/)
 *  - a keyword in the PR title
 *
 * @param {object} input
 * @param {string[]} input.labels PR labels (lowercased before matching)
 * @param {string} input.headBranch e.g. "codex/feat/foo"
 * @param {string} input.title
 * @param {object} config
 * @param {string[]} config.labels
 * @param {string[]} config.branchPrefixes
 * @param {string[]} config.keywords
 * @returns {{ agent: boolean, signal?: string }}
 */
function detectAgent(input, config) {
  const labels = input.labels.map((l) => l.toLowerCase());
  const title = input.title.toLowerCase();
  const branch = input.headBranch.toLowerCase();

  const label = config.labels.find((l) => labels.includes(l.toLowerCase()));
  if (label) return { agent: true, signal: `label "${label}"` };

  const prefix = config.branchPrefixes.find((p) =>
    branch.startsWith(p.toLowerCase())
  );
  if (prefix) return { agent: true, signal: `branch prefix "${prefix}"` };

  const keyword = config.keywords.find((k) =>
    title.includes(k.toLowerCase())
  );
  if (keyword) return { agent: true, signal: `title keyword "${keyword}"` };

  return { agent: false };
}

module.exports = { detectAgent };
