'use strict';

const core = require('@actions/core');
const github = require('@actions/github');

const { detectAgent } = require('./checks/detect');
const { findTodos } = require('./checks/todos');
const { findSecrets } = require('./checks/secrets');
const { findBadCommits } = require('./checks/commits');
const { evaluateCi } = require('./checks/ci');
const gqlClient = require('./github');
const { HEADER, buildMarkdown, toAnnotations } = require('./reporter');

function csv(value) {
  return (value || '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

// Code-side defaults mirror the `default:` values in action.yml. GitHub injects
// action.yml defaults into INPUT_* at runtime, but keeping them here too makes
// the action behave identically when invoked directly or in local dev.
const DEFAULTS = {
  'gate-agents-only': 'true',
  'agent-labels': 'codex-generated,agentic,ai-generated',
  'agent-branch-prefixes': 'codex/,claude-auto,gh-codex/',
  'agent-keywords': 'Generated by Codex,Generated by Claude,Generated by Copilot',
  'ignore-label': 'codex-guard-ignore',
  'check-todos': 'true',
  'todo-patterns': 'TODO,FIXME,XXX,HACK,WIP',
  'todo-blocking': 'true',
  'check-secrets': 'true',
  'check-commits': 'true',
  'commit-pattern':
    '(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\([a-z0-9-]+\\))?!?: .+|Merge .*|Revert .*|Initial commit|Update .+|Bump .+',
  'check-ci': 'true',
  'post-comment': 'true',
  'soft-fail': 'false',
};

function getInputs(coreImpl = core) {
  const raw = (name) => {
    const v = coreImpl.getInput(name);
    return v === '' && name in DEFAULTS ? DEFAULTS[name] : v;
  };
  // @actions/core's getBooleanInput throws on empty input, which breaks local
  // runs and any run where an input is simply unset — parse booleans ourselves.
  const toBool = (name) => String(raw(name)).toLowerCase() === 'true';
  return {
    token: raw('github-token') || process.env.GITHUB_TOKEN,
    gateAgentsOnly: toBool('gate-agents-only'),
    agentLabels: csv(raw('agent-labels')),
    agentBranchPrefixes: csv(raw('agent-branch-prefixes')),
    agentKeywords: csv(raw('agent-keywords')),
    checkTodos: toBool('check-todos'),
    todoPatterns: csv(raw('todo-patterns')),
    todosBlocking: toBool('todo-blocking'),
    checkSecrets: toBool('check-secrets'),
    secretExcludePaths: csv(raw('secret-exclude-paths')),
    checkCommits: toBool('check-commits'),
    commitPattern: raw('commit-pattern'),
    checkCi: toBool('check-ci'),
    ignoreCheckRunNames: csv(raw('ignore-check-run-names')),
    ignoreLabel: raw('ignore-label'),
    postComment: toBool('post-comment'),
    softFail: toBool('soft-fail'),
    prNumber: raw('pr-number'),
  };
}

/**
 * Resolve the PR we are gating from the event payload (works for
 * `pull_request`, `pull_request_target`, and `push`-style events when
 * `pr-number` is supplied manually).
 */
function resolvePr(context, prNumberInput) {
  const payload = context.payload || {};
  const pr = payload.pull_request || payload.issue?.pull_request;
  if (!pr) {
    if (prNumberInput) {
      return {
        number: Number(prNumberInput),
        headSha: payload.after || payload.sha,
        title: payload.pull_request?.title || '',
        headRef: payload.pull_request?.head?.ref || '',
        labels: [],
      };
    }
    return null;
  }
  return {
    number: pr.number,
    headSha: pr.head?.sha,
    title: pr.title || '',
    headRef: pr.head?.ref || '',
    labels: Array.isArray(pr.labels) ? pr.labels.map((l) => l.name || l) : [],
  };
}

async function run(deps = {}) {
  const coreImpl = deps.core || core;
  const gh = deps.github || github;
  const client = deps.client; // injected in tests
  const context = deps.context || gh.context;

  const inputs = getInputs(coreImpl);
  const pr = resolvePr(context, inputs.prNumber);

  if (!pr) {
    coreImpl.info(
      'codex-guard: no pull request in the event payload and no pr-number input — skipping.'
    );
    coreImpl.setOutput('result', 'skipped');
    return { result: 'skipped' };
  }
  if (!pr.headSha) {
    coreImpl.info('codex-guard: PR has no head sha — skipping.');
    coreImpl.setOutput('result', 'skipped');
    return { result: 'skipped' };
  }

  // Read the repository from the event payload first; fall back to context.repo
  // (which can throw when GITHUB_REPOSITORY is unset, e.g. running locally).
  let repo = context.payload?.repository;
  if (!repo) {
    try {
      repo = context.repo;
    } catch {
      repo = null;
    }
  }
  if (!repo) {
    throw new Error('Unable to determine the repository from the event context.');
  }

  const owner = repo.owner?.login || repo.owner?.name || (typeof repo.owner === 'string' ? repo.owner : null);
  const repoName = repo.name;
  const ctx = { owner, repo: repoName, prNumber: pr.number, headSha: pr.headSha };

  const ignoreLabel = (inputs.ignoreLabel || '').toLowerCase();
  if (pr.labels.some((l) => l.toLowerCase() === ignoreLabel)) {
    coreImpl.info(
      `codex-guard: PR carries the "${inputs.ignoreLabel}" label — skipping all checks.`
    );
    coreImpl.setOutput('result', 'pass');
    coreImpl.setOutput('detected-agent', 'false');
    coreImpl.setOutput('failed-checks', '');
    return { result: 'pass', detectedAgent: false, groups: emptyGroups() };
  }

  const detected = detectAgent(
    { labels: pr.labels, headBranch: pr.headRef, title: pr.title },
    {
      labels: inputs.agentLabels,
      branchPrefixes: inputs.agentBranchPrefixes,
      keywords: inputs.agentKeywords,
    }
  );

  if (inputs.gateAgentsOnly && !detected.agent) {
    coreImpl.info(
      'codex-guard: PR does not appear to be AI-generated — passing without checks.'
    );
    coreImpl.setOutput('result', 'pass');
    coreImpl.setOutput('detected-agent', 'false');
    return { result: 'pass', detectedAgent: false, groups: emptyGroups() };
  }

  let octokit;
  if (client) {
    octokit = client;
  } else if (inputs.token) {
    octokit = gh.getOctokit(inputs.token);
  } else {
    throw new Error('No GitHub token available. Set input github-token.');
  }

  const files = await gqlClient.getPrFiles(octokit, ctx);
  const commits = inputs.checkCommits
    ? await gqlClient.getPrCommits(octokit, ctx)
    : [];
  const ciResults = inputs.checkCi
    ? await gqlClient.getCiResults(octokit, ctx)
    : { statuses: [], checkRuns: [] };

  const groups = emptyGroups();
  if (inputs.checkTodos && inputs.todoPatterns.length) {
    groups.todos.push(...findTodos(files, inputs.todoPatterns));
  }
  if (inputs.checkSecrets) {
    groups.secrets.push(...findSecrets(files, inputs.secretExcludePaths));
  }
  if (inputs.checkCommits) {
    groups.commits.push(...findBadCommits(commits, { pattern: inputs.commitPattern }));
  }
  if (inputs.checkCi) {
    const ci = evaluateCi({
      statuses: ciResults.statuses,
      checkRuns: ciResults.checkRuns,
      ignoreNames: inputs.ignoreCheckRunNames,
    });
    groups.ci = { ok: ci.failed.length === 0, ...ci };
  }

  const anyBlockingFailure =
    (inputs.todosBlocking && groups.todos.length > 0) ||
    groups.secrets.length > 0 ||
    groups.commits.length > 0 ||
    groups.ci.failed.length > 0;

  const passed = !anyBlockingFailure;
  const outcome = inputs.softFail ? 'pass' : passed ? 'pass' : 'fail';

  // ---- Reporting ----------------------------------------------------------
  const checkName = 'Codex Guard';
  const annotations = toAnnotations(groups);
  const markdown = buildMarkdown({
    passed,
    groups,
    detected: detected.agent ? detected.signal : '',
  });

  await gqlClient
    .createCheckRun(octokit, ctx, {
      name: checkName,
      conclusion: passed && !inputs.softFail ? 'success' : 'failure',
      summaryText: passed
        ? 'Codex Guard passed — no blocking findings.'
        : 'Codex Guard found blocking issues. See annotations.',
      annotations,
      externalId: `codex-guard-${pr.number}`,
    })
    .catch((err) => coreImpl.warning(`Failed to create check run: ${err.message}`));

  if (inputs.postComment && !passed) {
    await gqlClient
      .postComment(octokit, ctx, markdown, HEADER)
      .catch((err) => coreImpl.warning(`Failed to post comment: ${err.message}`));
  }

  try {
    coreImpl.summary?.addRaw(markdown).write();
  } catch {
    /* step summary is best-effort */
  }

  // ---- Outputs ------------------------------------------------------------
  coreImpl.setOutput('result', outcome);
  coreImpl.setOutput('detected-agent', String(detected.agent));
  const failedChecks = [];
  if (inputs.todosBlocking && groups.todos.length) failedChecks.push('todos');
  if (groups.secrets.length) failedChecks.push('secrets');
  if (groups.commits.length) failedChecks.push('commits');
  if (groups.ci.failed.length) failedChecks.push('ci');
  coreImpl.setOutput('failed-checks', failedChecks.join(','));
  coreImpl.setOutput('todo-count', String(groups.todos.length));
  coreImpl.setOutput('secret-count', String(groups.secrets.length));
  coreImpl.setOutput('commit-count', String(groups.commits.length));
  coreImpl.setOutput('ci-failure-count', String(groups.ci.failed.length));

  if (outcome === 'fail' && !inputs.softFail) {
    coreImpl.setFailed(
      `Codex Guard failed (${failedChecks.join(', ') || 'checks'}). Fix the findings above and rerun.`
    );
  } else if (groups.todos.length && !inputs.todosBlocking) {
    coreImpl.notice(
      `Codex Guard: ${groups.todos.length} TODO/FIXME markers found (non-blocking).`
    );
  }

  return { result: outcome, detectedAgent: detected.agent, groups };
}

function emptyGroups() {
  return { todos: [], secrets: [], commits: [], ci: { ok: true, failed: [], pending: [], report: '' } };
}

module.exports = { run, getInputs, resolvePr };

// Entry point when executed by GitHub Actions.
if (require.main === module) {
  run().catch((err) => {
    core.setFailed(`codex-guard unexpected error: ${err.stack || err.message}`);
  });
}
