'use strict';

const core = require('@actions/core');
const github = require('@actions/github');

const { detectAgent } = require('./checks/detect');
const { findTodos } = require('./checks/todos');
const { findSecrets } = require('./checks/secrets');
const { findBadCommits } = require('./checks/commits');
const { evaluateCi } = require('./checks/ci');
const { evaluateContentCoverage, isCoverageIncomplete } = require('./checks/coverage');
const { loadRepoConfig, applyConfig } = require('./config');
const gqlClient = require('./github');
const { HEADER, buildMarkdown, toAnnotations } = require('./reporter');
const { codeSpan } = require('./markdown');

function csv(value) {
  return (value || '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

// Code-side defaults mirror the `default:` values in action.yml. GitHub injects
// action.yml defaults into INPUT_* at runtime, but keeping them here too makes
// the action behave identically when invoked directly or in local dev.
const DEFAULTS = {
  'gate-agents-only': 'true',
  'agent-labels': 'codex-generated,agentic,ai-generated',
  'agent-branch-prefixes': 'codex/,copilot/,claude-auto,gh-codex/',
  'agent-keywords': 'Generated by Codex,Generated by Claude,Generated by Copilot',
  'ignore-label': 'codex-guard-ignore',
  'check-todos': 'true',
  'todo-patterns': 'TODO,FIXME,XXX,HACK,WIP',
  'todo-blocking': 'true',
  'check-secrets': 'true',
  'check-commits': 'true',
  'commit-pattern':
    '(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\([a-z0-9-]+\\))?!?: .+|Merge .*|Revert .*|Initial commit|Update .+|Bump .+',
  'check-ci': 'true',
  'post-comment': 'true',
  'comment-mode': 'replace',
  'request-changes': 'false',
  'soft-fail': 'false',
  'config-path': '.github/codex-guard.yml',
  'fail-on': '',
  'sweep': 'false',
  'sweep-label': '',
  'sweep-base': 'main',
  'notify-users': '',
};

function getInputs(coreImpl = core) {
  const raw = (name) => {
    const v = coreImpl.getInput(name);
    return v === '' && name in DEFAULTS ? DEFAULTS[name] : v;
  };
  // @actions/core's getBooleanInput throws on empty input, which breaks local
  // runs and any run where an input is simply unset — parse booleans ourselves.
  const toBool = (name) => String(raw(name)).toLowerCase() === 'true';
  return {
    token: raw('github-token') || process.env.GITHUB_TOKEN,
    gateAgentsOnly: toBool('gate-agents-only'),
    agentLabels: csv(raw('agent-labels')),
    agentBranchPrefixes: csv(raw('agent-branch-prefixes')),
    agentKeywords: csv(raw('agent-keywords')),
    checkTodos: toBool('check-todos'),
    todoPatterns: csv(raw('todo-patterns')),
    todosBlocking: toBool('todo-blocking'),
    checkSecrets: toBool('check-secrets'),
    secretExcludePaths: csv(raw('secret-exclude-paths')),
    checkCommits: toBool('check-commits'),
    commitPattern: raw('commit-pattern'),
    checkCi: toBool('check-ci'),
    ignoreCheckRunNames: csv(raw('ignore-check-run-names')),
    ignoreLabel: raw('ignore-label'),
    postComment: toBool('post-comment'),
    commentMode: raw('comment-mode'),
    requestChanges: toBool('request-changes'),
    softFail: toBool('soft-fail'),
    configPath: raw('config-path'),
    failOn: csv(raw('fail-on')),
    sweep: toBool('sweep'),
    sweepLabel: raw('sweep-label'),
    sweepBase: raw('sweep-base'),
    notifyUsers: csv(raw('notify-users')),
    prNumber: raw('pr-number'),
  };
}

/**
 * Resolve the PR we are gating from the event payload (works for
 * `pull_request`, `pull_request_target`, and `push`-style events when
 * `pr-number` is supplied manually).
 */
function resolvePr(context, prNumberInput) {
  const payload = context.payload || {};
  const pr = payload.pull_request || payload.issue?.pull_request;
  if (!pr) {
    if (prNumberInput) {
      return {
        number: Number(prNumberInput),
        headSha: payload.after || payload.sha,
        title: payload.pull_request?.title || '',
        headRef: payload.pull_request?.head?.ref || '',
        labels: [],
      };
    }
    return null;
  }
  return {
    number: pr.number,
    headSha: pr.head?.sha,
    title: pr.title || '',
    headRef: pr.head?.ref || '',
    labels: Array.isArray(pr.labels) ? pr.labels.map((l) => l.name || l) : [],
  };
}

async function run(deps = {}) {
  const coreImpl = deps.core || core;
  const gh = deps.github || github;
  const client = deps.client; // injected in tests
  const context = deps.context || gh.context;

  let inputs = getInputs(coreImpl);
  const pr = resolvePr(context, inputs.prNumber);
  const sweepMode =
    !pr &&
    !inputs.prNumber &&
    (inputs.sweep || context.eventName === 'workflow_dispatch');

  if (!pr && !sweepMode) {
    coreImpl.info(
      'codex-guard: no pull request in the event payload and no pr-number input — skipping.'
    );
    coreImpl.setOutput('result', 'skipped');
    return { result: 'skipped' };
  }
  if (pr && !pr.headSha) {
    coreImpl.info('codex-guard: PR has no head sha — skipping.');
    coreImpl.setOutput('result', 'skipped');
    return { result: 'skipped' };
  }

  // Read the repository from the event payload first; fall back to context.repo
  // (which can throw when GITHUB_REPOSITORY is unset, e.g. running locally).
  let repo = context.payload?.repository;
  if (!repo) {
    try {
      repo = context.repo;
    } catch {
      repo = null;
    }
  }
  if (!repo) {
    throw new Error('Unable to determine the repository from the event context.');
  }

  const owner = repo.owner?.login || repo.owner?.name || (typeof repo.owner === 'string' ? repo.owner : null);
  const repoName = repo.name;
  const ctx = { owner, repo: repoName, prNumber: pr?.number ?? 0, headSha: pr?.headSha ?? null };

  let octokit;
  if (client) {
    octokit = client;
  } else if (inputs.token) {
    octokit = gh.getOctokit(inputs.token);
  }

  // Per-repo policy (.github/codex-guard.yml) overrides workflow inputs.
  const config = octokit
    ? await loadRepoConfig(octokit, ctx, inputs.configPath)
    : null;
  if (config) {
    inputs = applyConfig(inputs, config);
    coreImpl.info(`codex-guard: applied repo config (${inputs.configPath})`);
  }

  if (sweepMode) {
    if (!octokit) {
      throw new Error('No GitHub token available. Set input github-token.');
    }
    return await runSweep(octokit, ctx, inputs, coreImpl);
  }

  const ignoreLabel = (inputs.ignoreLabel || '').toLowerCase();
  if (pr.labels.some((l) => l.toLowerCase() === ignoreLabel)) {
    coreImpl.info(
      `codex-guard: PR carries the "${inputs.ignoreLabel}" label — skipping all checks.`
    );
    coreImpl.setOutput('result', 'pass');
    coreImpl.setOutput('detected-agent', 'false');
    coreImpl.setOutput('failed-checks', '');
    coreImpl.setOutput('findings-json', '{}');
    return { result: 'pass', detectedAgent: false, groups: emptyGroups() };
  }

  const detected = detectAgent(
    { labels: pr.labels, headBranch: pr.headRef, title: pr.title },
    {
      labels: inputs.agentLabels,
      branchPrefixes: inputs.agentBranchPrefixes,
      keywords: inputs.agentKeywords,
    }
  );

  if (inputs.gateAgentsOnly && !detected.agent) {
    coreImpl.info(
      'codex-guard: PR does not appear to be AI-generated — passing without checks.'
    );
    coreImpl.setOutput('result', 'pass');
    coreImpl.setOutput('detected-agent', 'false');
    coreImpl.setOutput('findings-json', '{}');
    return { result: 'pass', detectedAgent: false, groups: emptyGroups() };
  }

  if (!octokit) {
    throw new Error('No GitHub token available. Set input github-token.');
  }

  const { groups, triggered } = await inspectPr(octokit, ctx, inputs);

  const passed = triggered.length === 0;
  const outcome = inputs.softFail ? 'pass' : passed ? 'pass' : 'fail';
  const incompleteCoverage = isCoverageIncomplete(groups.coverage);
  const incompleteCiVisibility = inputs.checkCi && groups.ci.complete === false;
  const pendingCi = inputs.checkCi && groups.ci.settled === false;

  // ---- Reporting ----------------------------------------------------------
  const checkName = 'Codex Guard';
  const annotations = toAnnotations(groups);
  let markdown = buildMarkdown({
    passed,
    observing: inputs.softFail,
    groups,
    detected: detected.agent ? detected.signal : '',
  });
  if (!passed && inputs.notifyUsers.length) {
    markdown += `\n\n---\n${inputs.notifyUsers.map((u) => `@${u}`).join(' ')} — please review the findings above.`;
  }

  await gqlClient
    .createCheckRun(octokit, ctx, {
      name: checkName,
      conclusion: !passed
        ? inputs.softFail ? 'neutral' : 'failure'
        : incompleteCoverage || incompleteCiVisibility || pendingCi ? 'neutral' : 'success',
      summaryText: markdown,
      annotations,
      externalId: `codex-guard-${pr.number}`,
    })
    .catch((err) => coreImpl.warning(`Failed to create check run: ${err.message}`));

  if (!passed && inputs.postComment && inputs.commentMode !== 'none') {
    const commentOutcome = await gqlClient
      .upsertComment(octokit, ctx, markdown, HEADER, inputs.commentMode)
      .catch((err) => {
        coreImpl.warning(`Failed to update PR comment: ${err.message}`);
        return false;
      });
    if (commentOutcome === 'updated') {
      coreImpl.notice('Codex Guard: report comment updated in place.');
    }
  }

  if (inputs.requestChanges && !passed && !inputs.softFail) {
    await gqlClient
      .requestChanges(
        octokit,
        ctx,
        'Codex Guard found blocking issues (see check annotations and the report above). Requesting changes until they are resolved.'
      )
      .catch((err) => coreImpl.warning(`Failed to request changes: ${err.message}`));
  }

  try {
    coreImpl.summary?.addRaw(markdown).write();
  } catch {
    /* step summary is best-effort */
  }

  // ---- Outputs ------------------------------------------------------------
  coreImpl.setOutput('result', outcome);
  coreImpl.setOutput('detected-agent', String(detected.agent));
  coreImpl.setOutput('failed-checks', triggered.join(','));
  coreImpl.setOutput('todo-count', String(groups.todos.length));
  coreImpl.setOutput('secret-count', String(groups.secrets.length));
  coreImpl.setOutput('commit-count', String(groups.commits.length));
  coreImpl.setOutput('ci-failure-count', String(groups.ci.failed.length));
  coreImpl.setOutput(
    'content-scan-coverage',
    groups.coverage.enabled
      ? `${groups.coverage.scanned}/${groups.coverage.eligible}`
      : 'disabled'
  );
  coreImpl.setOutput('unscanned-file-count', String(groups.coverage.unscanned.length));
  coreImpl.setOutput(
    'findings-json',
    JSON.stringify({
      todos: groups.todos,
      secrets: groups.secrets,
      commits: groups.commits,
      ci: {
        ok: groups.ci.ok,
        failed: groups.ci.failed,
        pending: groups.ci.pending,
        errors: groups.ci.errors,
        complete: groups.ci.complete,
        settled: groups.ci.settled,
        report: groups.ci.report,
      },
      coverage: groups.coverage,
    })
  );

  if (outcome === 'fail' && !inputs.softFail) {
    coreImpl.setFailed(
      `Codex Guard failed (${triggered.join(', ') || 'checks'}). Fix the findings above and rerun.`
    );
  } else if (groups.todos.length && !triggered.includes('todos')) {
    coreImpl.notice(
      `Codex Guard: ${groups.todos.length} TODO/FIXME markers found (non-blocking).`
    );
  }

  return { result: outcome, detectedAgent: detected.agent, groups };
}

/** Fetch and inspect a single PR: files/commits/CI → findings + blocking list. */
async function inspectPr(octokit, ctx, inputs) {
  const files = await gqlClient.getPrFiles(octokit, ctx);
  const commits = inputs.checkCommits
    ? await gqlClient.getPrCommits(octokit, ctx)
    : [];
  const ciResults = inputs.checkCi
    ? await gqlClient.getCiResults(octokit, ctx)
    : { statuses: [], checkRuns: [], errors: [] };

  const groups = emptyGroups();
  groups.coverage = evaluateContentCoverage(files, {
    enabled: inputs.checkTodos || inputs.checkSecrets,
  });
  if (inputs.checkTodos && inputs.todoPatterns.length) {
    groups.todos.push(...findTodos(files, inputs.todoPatterns));
  }
  if (inputs.checkSecrets) {
    groups.secrets.push(...findSecrets(files, inputs.secretExcludePaths));
  }
  if (inputs.checkCommits) {
    groups.commits.push(...findBadCommits(commits, { pattern: inputs.commitPattern }));
  }
  if (inputs.checkCi) {
    const ci = evaluateCi({
      statuses: ciResults.statuses,
      checkRuns: ciResults.checkRuns,
      errors: ciResults.errors,
      ignoreNames: inputs.ignoreCheckRunNames,
    });
    groups.ci = { ok: ci.failed.length === 0 && ci.complete && ci.settled, ...ci };
  }

  // Which checks count as blocking. `fail-on` selects them explicitly;
  // otherwise the legacy behavior applies (todos governed by todo-blocking,
  // the rest always blocking).
  const triggered = [];
  if (inputs.failOn && inputs.failOn.length) {
    const blocks = (name) => inputs.failOn.includes(name);
    if (blocks('todos') && groups.todos.length) triggered.push('todos');
    if (blocks('secrets') && groups.secrets.length) triggered.push('secrets');
    if (blocks('commits') && groups.commits.length) triggered.push('commits');
    if (blocks('ci') && groups.ci.failed.length) triggered.push('ci');
  } else {
    if (inputs.todosBlocking && groups.todos.length) triggered.push('todos');
    if (groups.secrets.length) triggered.push('secrets');
    if (groups.commits.length) triggered.push('commits');
    if (groups.ci.failed.length) triggered.push('ci');
  }
  return { groups, triggered };
}

/** Sweep mode (workflow_dispatch): inspect every open agent-generated PR. */
async function runSweep(octokit, repoCtx, inputs, coreImpl) {
  coreImpl.notice('codex-guard: sweep mode — scanning open pull requests.');

  const open = [];
  let page = 1;
  for (;;) {
    const { data } = await octokit.rest.pulls.list({
      owner: repoCtx.owner,
      repo: repoCtx.repo,
      state: 'open',
      per_page: 100,
      page,
    });
    open.push(...data);
    if (data.length < 100) break;
    page += 1;
  }

  const base = (inputs.sweepBase || 'main').toLowerCase();
  const sweepLabel = (inputs.sweepLabel || '').toLowerCase();
  const ignoreLabel = (inputs.ignoreLabel || '').toLowerCase();
  const scanned = [];
  const skipped = [];

  for (const pr of open) {
    if ((pr.base?.ref || '').toLowerCase() !== base) continue;
    const labels = Array.isArray(pr.labels) ? pr.labels.map((l) => l.name || l) : [];
    if (ignoreLabel && labels.some((l) => l.toLowerCase() === ignoreLabel)) {
      skipped.push({ pr, reason: `ignore label "${inputs.ignoreLabel}"` });
      continue;
    }
    if (sweepLabel && !labels.some((l) => l.toLowerCase() === sweepLabel)) {
      skipped.push({ pr, reason: `missing sweep label "${inputs.sweepLabel}"` });
      continue;
    }
    const detected = detectAgent(
      { labels, headBranch: pr.head?.ref || '', title: pr.title || '' },
      {
        labels: inputs.agentLabels,
        branchPrefixes: inputs.agentBranchPrefixes,
        keywords: inputs.agentKeywords,
      }
    );
    if (inputs.gateAgentsOnly && !detected.agent) {
      skipped.push({ pr, reason: 'not agent-generated' });
      continue;
    }
    if (!pr.head?.sha) {
      skipped.push({ pr, reason: 'no head sha' });
      continue;
    }
    const prCtx = {
      owner: repoCtx.owner,
      repo: repoCtx.repo,
      prNumber: pr.number,
      headSha: pr.head.sha,
    };
    try {
      const { groups, triggered } = await inspectPr(octokit, prCtx, inputs);
      scanned.push({ pr, groups, triggered });
    } catch (err) {
      scanned.push({ pr, groups: emptyGroups(), triggered: ['error'], error: err.message });
    }
  }

  const lines = ['# 🤖 Codex Guard — sweep report', ''];
  lines.push(
    `Inspected ${scanned.length} agent-generated PR${scanned.length === 1 ? '' : 's'}; ` +
      `${skipped.length} skipped (human-authored or ignored).`,
    ''
  );
  for (const s of scanned) {
    const verdict = s.triggered.length ? `❌ blocking (${s.triggered.join(', ')})` : '✅';
    lines.push(
      `- **#${s.pr.number}** ${codeSpan(s.pr.title, 300)} — ${verdict}; todos ${s.groups.todos.length}, ` +
        `secrets ${s.groups.secrets.length}, commits ${s.groups.commits.length}, ` +
        `ci-failures ${s.groups.ci.failed.length}, coverage ` +
        `${s.groups.coverage.enabled ? `${s.groups.coverage.scanned}/${s.groups.coverage.eligible}` : 'disabled'}` +
        (s.groups.ci.complete ? '' : ', ci-visibility incomplete') +
        (s.groups.ci.settled ? '' : ', ci pending') +
        (s.error ? ` — error: ${codeSpan(s.error, 500)}` : '')
    );
  }
  for (const s of skipped) {
    lines.push(
      `- #${s.pr.number} ${codeSpan(s.pr.title, 300)} — skipped (${codeSpan(s.reason, 200)})`
    );
  }
  const report = lines.join('\n');

  coreImpl.setOutput('result', 'sweep');
  coreImpl.setOutput('sweep-scanned', String(scanned.length));
  coreImpl.setOutput('sweep-failed', String(scanned.filter((s) => s.triggered.length).length));
  coreImpl.setOutput(
    'sweep-json',
    JSON.stringify(
      scanned.map((s) => ({
        number: s.pr.number,
        title: s.pr.title,
        triggered: s.triggered,
        counts: {
          todos: s.groups.todos.length,
          secrets: s.groups.secrets.length,
          commits: s.groups.commits.length,
          ci: s.groups.ci.failed.length,
        },
        coverage: s.groups.coverage,
      }))
    )
  );

  try {
    coreImpl.summary?.addRaw(report).write();
  } catch {
    /* step summary is best-effort */
  }
  coreImpl.setOutput('sweep-report', report);
  return { result: 'sweep', scanned, skipped };
}

function emptyGroups() {
  return {
    todos: [],
    secrets: [],
    commits: [],
    ci: {
      ok: true,
      failed: [],
      pending: [],
      errors: [],
      complete: true,
      settled: true,
      report: '',
    },
    coverage: {
      enabled: false,
      eligible: 0,
      scanned: 0,
      unscanned: [],
      apiLimitReached: false,
    },
  };
}

module.exports = { run, getInputs, resolvePr };

// Entry point when executed by GitHub Actions.
if (require.main === module) {
  run().catch((err) => {
    core.setFailed(`codex-guard unexpected error: ${err.stack || err.message}`);
  });
}
